name = "Rectangle"
uuid = "9a9db56c-8f71-5460-add5-cb450131785e"
repo = "https://github.com/sambitdash/Rectangle.jl.git"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.0"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PyCall", "PyPlot"]
